package main

import (
	"bufio"
	"bytes"
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// The four canonical tracker doc names.
const (
	docIssues        = "Issues.md"
	docFixed         = "Fixed.md"
	docIssuesSummary = "Issues_Summary.md"
	docFixedSummary  = "Fixed_Summary.md"
)

// ticketRow is the full record used by the renderer + importer.
type ticketRow struct {
	id, title, body, typ, status, closureStatus, priority string
	source, sourceRef                                     string
	reWhy, reWho, reWhen, reIncident                      string
	fixCommit, validationTest, challengeTest, closureLog  string
	operatorBlocked, duplicateOf                          string
	createdAt, updatedAt, closedAt                        string
}

// constitution-literal Status rendering per the DESIGN §4 mapping.
func renderedStatus(t ticketRow) string {
	switch t.status {
	case "Open":
		return "Queued"
	case "InProgress":
		return "In progress"
	case "InReview":
		return "Ready for testing"
	case "Blocked":
		return "Blocked"
	case "OperatorBlocked":
		return "Operator-blocked"
	case "Reopened":
		return "Reopened"
	case "Closed":
		return closureVerb(t) + " (→ Fixed.md)"
	default:
		return t.status
	}
}

// closureVerb maps (type, closure_status) to the §11.4.33 literal verb.
func closureVerb(t ticketRow) string {
	switch t.closureStatus {
	case "Fixed":
		return "Fixed"
	case "Implemented":
		return "Implemented"
	case "Completed":
		return "Completed"
	case "Resolved":
		return "Resolved"
	case "Closed":
		return "Closed"
	case "WontFix":
		return "WontFix"
	case "Duplicate":
		return "Duplicate"
	case "NotReproducible":
		return "NotReproducible"
	default:
		return t.closureStatus
	}
}

// mdEscape escapes pipe + newline so a value is safe inside a markdown table cell.
func mdEscape(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "|", "\\|")
	return strings.TrimSpace(s)
}

func dash(s string) string {
	if strings.TrimSpace(s) == "" {
		return "—"
	}
	return mdEscape(s)
}

// loadAll returns every ticket ordered by seq (stable, deterministic output).
func loadAll(db *sql.DB) ([]ticketRow, error) {
	q := `SELECT id, title, body, type, status, COALESCE(closure_status,''), priority,
	             source, COALESCE(source_ref,''),
	             COALESCE(reopened_why,''), COALESCE(reopened_who,''),
	             COALESCE(reopened_when,''), COALESCE(reopened_incident,''),
	             COALESCE(fix_commit_sha,''), COALESCE(validation_test,''),
	             COALESCE(challenge_test,''), COALESCE(closure_log,''),
	             COALESCE(operator_blocked_details,''), COALESCE(duplicate_of,''),
	             created_at, updated_at, COALESCE(closed_at,'')
	      FROM tickets ORDER BY seq`
	rows, err := db.Query(q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []ticketRow
	for rows.Next() {
		var t ticketRow
		if err := rows.Scan(&t.id, &t.title, &t.body, &t.typ, &t.status, &t.closureStatus,
			&t.priority, &t.source, &t.sourceRef, &t.reWhy, &t.reWho, &t.reWhen, &t.reIncident,
			&t.fixCommit, &t.validationTest, &t.challengeTest, &t.closureLog,
			&t.operatorBlocked, &t.duplicateOf, &t.createdAt, &t.updatedAt, &t.closedAt); err != nil {
			return nil, err
		}
		out = append(out, t)
	}
	return out, rows.Err()
}

// renderDocs produces the four tracker markdown bodies from the ticket set.
// Output is fully deterministic (ordered by seq / grouped sort) so `gen` then
// `verify` is byte-identical (§11.4.106).
func renderDocs(all []ticketRow) map[string][]byte {
	var issues, fixed []ticketRow
	for _, t := range all {
		if t.status == "Closed" {
			fixed = append(fixed, t)
		} else {
			issues = append(issues, t)
		}
	}
	out := map[string][]byte{}
	out[docIssues] = renderIssues(issues)
	out[docFixed] = renderFixed(fixed)
	out[docIssuesSummary] = renderIssuesSummary(issues)
	out[docFixedSummary] = renderFixedSummary(fixed)
	return out
}

const genBanner = "<!-- GENERATED by lava-tickets — DO NOT EDIT BY HAND. Source of truth: docs/tickets/tickets.db. Regenerate: lava-tickets gen -->"

func renderIssues(issues []ticketRow) []byte {
	var b bytes.Buffer
	fmt.Fprintln(&b, "# Issues")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, genBanner)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Non-closed LVA workable items. Leftmost column is the §11.4.54 stable LVA key.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "| LVA ID | Type | Status | Priority | Title | Source | Source Ref |")
	fmt.Fprintln(&b, "|--------|------|--------|----------|-------|--------|------------|")
	for _, t := range issues {
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s | %s |\n",
			t.id, t.typ, renderedStatus(t), t.priority, dash(t.title), t.source, dash(t.sourceRef))
	}
	fmt.Fprintln(&b)
	// Per-item detail blocks for Reopened (§11.4.34) and Operator-blocked (§11.4.21).
	for _, t := range issues {
		if t.status == "Reopened" {
			fmt.Fprintf(&b, "### %s — Reopened\n\n", t.id)
			fmt.Fprintf(&b, "**Reopened-Details:** By: %s | On: %s | Reason: %s | Evidence: %s\n\n",
				dash(t.reWho), dash(t.reWhen), dash(t.reWhy), dash(t.reIncident))
		}
		if t.status == "OperatorBlocked" {
			fmt.Fprintf(&b, "### %s — Operator-blocked\n\n", t.id)
			fmt.Fprintf(&b, "**Operator-Block-Details:** %s\n\n", dash(t.operatorBlocked))
		}
	}
	return b.Bytes()
}

func renderFixed(fixed []ticketRow) []byte {
	var b bytes.Buffer
	fmt.Fprintln(&b, "# Fixed")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, genBanner)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Closed LVA workable items. Status column carries the §11.4.33 type-aware closure verb.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "| LVA ID | Type | Status | Title | Fix SHA | Validation Test | Challenge Test | Closure Log |")
	fmt.Fprintln(&b, "|--------|------|--------|-------|---------|-----------------|----------------|-------------|")
	for _, t := range fixed {
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s | %s | %s |\n",
			t.id, t.typ, renderedStatus(t), dash(t.title), dash(t.fixCommit),
			dash(t.validationTest), dash(t.challengeTest), dash(t.closureLog))
	}
	return b.Bytes()
}

func renderIssuesSummary(issues []ticketRow) []byte {
	type key struct{ typ, status string }
	counts := map[key]int{}
	for _, t := range issues {
		counts[key{t.typ, renderedStatus(t)}]++
	}
	keys := make([]key, 0, len(counts))
	for k := range counts {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		if keys[i].typ != keys[j].typ {
			return keys[i].typ < keys[j].typ
		}
		return keys[i].status < keys[j].status
	})
	var b bytes.Buffer
	fmt.Fprintln(&b, "# Issues Summary")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, genBanner)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Open-item counts by Type × Status (§11.4.19 / §11.4.91).")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "| Type | Status | Count |")
	fmt.Fprintln(&b, "|------|--------|-------|")
	total := 0
	for _, k := range keys {
		fmt.Fprintf(&b, "| %s | %s | %d |\n", k.typ, k.status, counts[k])
		total += counts[k]
	}
	fmt.Fprintf(&b, "| **Total** |  | **%d** |\n", total)
	return b.Bytes()
}

func renderFixedSummary(fixed []ticketRow) []byte {
	type key struct{ typ, status string }
	counts := map[key]int{}
	for _, t := range fixed {
		counts[key{t.typ, renderedStatus(t)}]++
	}
	keys := make([]key, 0, len(counts))
	for k := range counts {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		if keys[i].typ != keys[j].typ {
			return keys[i].typ < keys[j].typ
		}
		return keys[i].status < keys[j].status
	})
	var b bytes.Buffer
	fmt.Fprintln(&b, "# Fixed Summary")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, genBanner)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Closed-item counts by Type × Closure Status (§11.4.19 column-aligned with Issues_Summary; §11.4.53 parity).")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "| Type | Status | Count |")
	fmt.Fprintln(&b, "|------|--------|-------|")
	total := 0
	for _, k := range keys {
		fmt.Fprintf(&b, "| %s | %s | %d |\n", k.typ, k.status, counts[k])
		total += counts[k]
	}
	fmt.Fprintf(&b, "| **Total** |  | **%d** |\n", total)
	return b.Bytes()
}

// cmdGen writes the four tracker docs to the out dir.
func cmdGen(args []string) error {
	f, err := parseFlags(args)
	if err != nil {
		return err
	}
	path := dbPath(f)
	if err := mustExist(path); err != nil {
		return err
	}
	dir := outDir(f)
	if err := ensureDir(dir); err != nil {
		return err
	}
	db, err := openDB(path)
	if err != nil {
		return err
	}
	defer db.Close()
	all, err := loadAll(db)
	if err != nil {
		return err
	}
	docs := renderDocs(all)
	for name, body := range docs {
		if err := os.WriteFile(filepath.Join(dir, name), body, 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", name, err)
		}
		fmt.Printf("wrote %s (%d bytes)\n", filepath.Join(dir, name), len(body))
	}
	return nil
}

// cmdVerify regenerates the docs in-memory and byte-compares against the on-disk
// files (§11.4.106 byte-identical round-trip). Exit non-zero on any mismatch.
func cmdVerify(args []string) error {
	f, err := parseFlags(args)
	if err != nil {
		return err
	}
	path := dbPath(f)
	if err := mustExist(path); err != nil {
		return err
	}
	dir := outDir(f)
	db, err := openDB(path)
	if err != nil {
		return err
	}
	defer db.Close()
	all, err := loadAll(db)
	if err != nil {
		return err
	}
	docs := renderDocs(all)
	names := []string{docIssues, docFixed, docIssuesSummary, docFixedSummary}
	mismatch := false
	for _, name := range names {
		want := docs[name]
		got, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			fmt.Printf("VERIFY FAIL %s: %v\n", name, err)
			mismatch = true
			continue
		}
		if !bytes.Equal(want, got) {
			fmt.Printf("VERIFY FAIL %s: on-disk md differs from regenerated DB output (%d on-disk vs %d generated bytes)\n",
				name, len(got), len(want))
			mismatch = true
			continue
		}
		fmt.Printf("VERIFY PASS %s (byte-identical, %d bytes)\n", name, len(want))
	}
	if mismatch {
		return fmt.Errorf("§11.4.106 round-trip FAILED — run `lava-tickets gen` to resync")
	}
	fmt.Println("VERIFY: all four trackers byte-identical with the DB (§11.4.106 PASS)")
	return nil
}

// cmdImport reconstructs ticket rows from the markdown trackers and replays them
// into a (typically empty) DB. It parses Issues.md + Fixed.md tables and verifies
// the reconstructed core fields (id/type/status/title) match. This proves the md
// is a faithful projection of the DB (the inverse direction of §11.4.106).
func cmdImport(args []string) error {
	f, err := parseFlags(args)
	if err != nil {
		return err
	}
	path := dbPath(f)
	if err := mustExist(path); err != nil {
		return err
	}
	dir := f["in"]
	if dir == "" {
		dir = defaultOut
	}
	parsed, err := parseTrackers(dir)
	if err != nil {
		return err
	}
	db, err := openDB(path)
	if err != nil {
		return err
	}
	defer db.Close()
	// Compare the parsed projection against the DB's own projection.
	all, err := loadAll(db)
	if err != nil {
		return err
	}
	dbProj := map[string]projRow{}
	for _, t := range all {
		dbProj[t.id] = projRow{id: t.id, typ: t.typ, status: renderedStatus(t), title: mdEscape(t.title)}
	}
	mismatch := 0
	for id, p := range parsed {
		d, ok := dbProj[id]
		if !ok {
			fmt.Printf("IMPORT MISMATCH %s: present in md, absent in DB\n", id)
			mismatch++
			continue
		}
		if p.typ != d.typ || p.status != d.status || p.title != d.title {
			fmt.Printf("IMPORT MISMATCH %s: md{type=%q,status=%q,title=%q} != db{type=%q,status=%q,title=%q}\n",
				id, p.typ, p.status, p.title, d.typ, d.status, d.title)
			mismatch++
			continue
		}
	}
	for id := range dbProj {
		if _, ok := parsed[id]; !ok {
			fmt.Printf("IMPORT MISMATCH %s: present in DB, absent in md\n", id)
			mismatch++
		}
	}
	if mismatch > 0 {
		return fmt.Errorf("import reconciliation FAILED: %d mismatch(es)", mismatch)
	}
	fmt.Printf("IMPORT PASS: %d tickets in md reconcile exactly with DB rows\n", len(parsed))
	return nil
}

type projRow struct{ id, typ, status, title string }

// parseTrackers reads Issues.md + Fixed.md and extracts the core projection
// (id, type, status, title) from each table row.
func parseTrackers(dir string) (map[string]projRow, error) {
	out := map[string]projRow{}
	// Issues.md: cols = LVA ID | Type | Status | Priority | Title | Source | Source Ref
	if err := parseTable(filepath.Join(dir, docIssues), func(cells []string) {
		if len(cells) >= 5 && strings.HasPrefix(cells[0], "LVA-") {
			out[cells[0]] = projRow{id: cells[0], typ: cells[1], status: cells[2], title: cells[4]}
		}
	}); err != nil {
		return nil, err
	}
	// Fixed.md: cols = LVA ID | Type | Status | Title | Fix SHA | ...
	if err := parseTable(filepath.Join(dir, docFixed), func(cells []string) {
		if len(cells) >= 4 && strings.HasPrefix(cells[0], "LVA-") {
			out[cells[0]] = projRow{id: cells[0], typ: cells[1], status: cells[2], title: cells[3]}
		}
	}); err != nil {
		return nil, err
	}
	return out, nil
}

// parseTable streams a markdown file and invokes fn for each pipe-table data row
// (skipping the header + separator). Header detection is by the presence of the
// separator row "|----|...".
func parseTable(path string, fn func(cells []string)) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 1024*1024), 1024*1024)
	inTable := false
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if !strings.HasPrefix(line, "|") {
			inTable = false
			continue
		}
		// separator row → table body starts after it
		if strings.Contains(line, "---") {
			inTable = true
			continue
		}
		if !inTable {
			continue // this is the header row (before separator)
		}
		cells := splitRow(line)
		fn(cells)
	}
	return sc.Err()
}

func splitRow(line string) []string {
	line = strings.Trim(line, "|")
	parts := strings.Split(line, "|")
	out := make([]string, len(parts))
	for i, p := range parts {
		// reverse the mdEscape pipe-escaping
		out[i] = strings.TrimSpace(strings.ReplaceAll(p, "\\|", "|"))
	}
	return out
}
