// Package ticket — adapter unit tests.
//
// Per §6.J / §6.AB: every public adapter method exercised against the REAL
// HelixQA Generator wired to a real filesystem (t.TempDir). No mocks of
// the SUT. Each test asserts on user-visible state (file on disk, file
// content match against §6.O schema), not on call counts.
//
// Per Phase 4-C-3 design doc §F.1: every test in this file is paired with
// a falsifiability rehearsal recorded in the Phase 4-C-3 commit body.
package ticket

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"
)

// fullClosureInput returns a fully-populated ClosureLogInput suitable for
// schema-matching assertions. Mirrors the shape observed across existing
// .lava-ci-evidence/crashlytics-resolved/ files.
func fullClosureInput() ClosureLogInput {
	return ClosureLogInput{
		CrashlyticsID:   "a29412cf6566d0a71b06df416610be57",
		Slug:            "rutracker-loginusecase-unknown",
		Date:            time.Date(2026, 5, 14, 12, 0, 0, 0, time.UTC),
		Title:           "lava.tracker.rutracker.domain.LoginUseCase.invoke",
		Subtitle:        "lava.tracker.rutracker.model.Unknown",
		Stack:           "LoginUseCase.kt:40 → invokeSuspend → main looper",
		Type:            "FATAL",
		Device:          "Samsung Galaxy S23 Ultra (SM-S918B), Android 16",
		Version:         "1.2.8 (1028) release — 1 event 2026-05-07",
		StateAtClosure:  "OPEN (operator marks closed)",
		RootCause:       "LoginUseCase handles 4 cases; case 4 throws singleton Unknown.",
		Fix:             "RuTrackerNetworkApi.login wraps invoke with try/catch; CancellationException re-thrown, other Throwables → WrongCredits fallback.",
		ValidationTest:  "core/tracker/rutracker/src/test/.../RuTrackerNetworkApiLoginUnknownRegressionTest.kt",
		ChallengeTest:   "owed — covered transitively by C04 login flow Challenge",
		ClosureProtocol: "Operator marks issue closed in Firebase Console; LoginUseCase itself unchanged.",
		FixCommitSHA:    "abc1234deadbeef",
		Labels:          []string{"rutracker", "auth"},
	}
}

// TestNewGenerator_BasicConstruction verifies the constructor wires the
// outputDir correctly and does NOT touch the filesystem at construction.
func TestNewGenerator_BasicConstruction(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "subdir-does-not-exist-yet")
	g := NewGenerator(dir)

	if got, want := g.OutputDir(), dir; got != want {
		t.Errorf("OutputDir() = %q; want %q", got, want)
	}
	// Constructor must not have created the directory.
	if _, err := os.Stat(dir); !os.IsNotExist(err) {
		t.Errorf("constructor created outputDir %q; expected not-yet-exists", dir)
	}
}

// TestGenerateClosureLog_HappyPath is the primary anti-bluff assertion
// (per §6.J.3): the file MUST exist at the expected §6.O path with the
// expected §6.O schema sections. Mutating any of the rendered headings
// makes this test fail with a clear assertion.
func TestGenerateClosureLog_HappyPath(t *testing.T) {
	dir := t.TempDir()
	g := NewGenerator(dir)

	in := fullClosureInput()
	path, err := g.GenerateClosureLog(context.Background(), in)
	if err != nil {
		t.Fatalf("GenerateClosureLog error: %v", err)
	}

	// Filename matches §6.O pattern: <YYYY-MM-DD>-<slug>.md
	wantName := "2026-05-14-rutracker-loginusecase-unknown.md"
	if got := filepath.Base(path); got != wantName {
		t.Errorf("filename = %q; want %q", got, wantName)
	}

	// File exists on disk (user-visible state).
	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("written file not found: %v", err)
	}
	if info.Size() == 0 {
		t.Fatalf("written file is empty: %s", path)
	}

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read written file: %v", err)
	}
	s := string(content)

	// §6.O schema required sections.
	required := []string{
		"# Crashlytics issue a29412cf6566d0a71b06df416610be57 — closure log",
		"**Issue ID:** `a29412cf6566d0a71b06df416610be57`",
		"**Title:** `lava.tracker.rutracker.domain.LoginUseCase.invoke`",
		"**Type:** FATAL",
		"**Device:** Samsung Galaxy S23 Ultra (SM-S918B), Android 16",
		"**Version:** 1.2.8 (1028) release — 1 event 2026-05-07",
		"**State at closure:** OPEN (operator marks closed)",
		"**Closure date:** 2026-05-14",
		"**Fix commit:** `abc1234deadbeef`",
		"## Root cause",
		"## Fix",
		"## Validation test (per §6.O + §6.AB)",
		"## Challenge Test (per §6.O + §6.AE)",
		"## Closure protocol",
		"Generated by lava-api-go/internal/qa/ticket",
	}
	for _, want := range required {
		if !strings.Contains(s, want) {
			t.Errorf("rendered markdown missing required fragment %q\nfull output:\n%s", want, s)
		}
	}

	// Body content actually included (not just headings).
	bodyChecks := []string{
		"LoginUseCase handles 4 cases",
		"RuTrackerNetworkApi.login wraps invoke",
		"RuTrackerNetworkApiLoginUnknownRegressionTest.kt",
		"Operator marks issue closed in Firebase Console",
	}
	for _, want := range bodyChecks {
		if !strings.Contains(s, want) {
			t.Errorf("rendered markdown missing required body content %q", want)
		}
	}
}

// TestGenerateClosureLog_RejectsEmptyCrashlyticsID is the §6.J posture
// against silently writing a file that claims to close an unidentified
// issue. The error MUST be ErrEmptyCrashlyticsID (so callers can match
// it) AND no file MUST be written.
func TestGenerateClosureLog_RejectsEmptyCrashlyticsID(t *testing.T) {
	dir := t.TempDir()
	g := NewGenerator(dir)

	in := fullClosureInput()
	in.CrashlyticsID = ""

	path, err := g.GenerateClosureLog(context.Background(), in)
	if !errors.Is(err, ErrEmptyCrashlyticsID) {
		t.Errorf("err = %v; want %v", err, ErrEmptyCrashlyticsID)
	}
	if path != "" {
		t.Errorf("path = %q; want empty on error", path)
	}
	// No file should have been written.
	entries, _ := os.ReadDir(dir)
	if len(entries) != 0 {
		t.Errorf("found %d files in output dir after rejected input; want 0", len(entries))
	}
}

// TestGenerateClosureLog_RejectsEmptySlug guards against same-day filename
// collisions when slug is omitted ("2026-05-16-.md" would silently
// overwrite a prior call).
func TestGenerateClosureLog_RejectsEmptySlug(t *testing.T) {
	dir := t.TempDir()
	g := NewGenerator(dir)

	in := fullClosureInput()
	in.Slug = ""

	path, err := g.GenerateClosureLog(context.Background(), in)
	if !errors.Is(err, ErrEmptySlug) {
		t.Errorf("err = %v; want %v", err, ErrEmptySlug)
	}
	if path != "" {
		t.Errorf("path = %q; want empty on error", path)
	}
}

// TestGenerateClosureLog_RejectsWhitespaceCrashlyticsID confirms the
// trim is performed (callers occasionally paste IDs with surrounding
// whitespace from the Console).
func TestGenerateClosureLog_RejectsWhitespaceCrashlyticsID(t *testing.T) {
	dir := t.TempDir()
	g := NewGenerator(dir)

	in := fullClosureInput()
	in.CrashlyticsID = "   \t  "

	_, err := g.GenerateClosureLog(context.Background(), in)
	if !errors.Is(err, ErrEmptyCrashlyticsID) {
		t.Errorf("err = %v; want %v for whitespace-only ID", err, ErrEmptyCrashlyticsID)
	}
}

// TestGenerateClosureLog_DateZeroUsesNow ensures the auto-now fallback
// produces a file whose date prefix is today's UTC date.
func TestGenerateClosureLog_DateZeroUsesNow(t *testing.T) {
	dir := t.TempDir()
	g := NewGenerator(dir)

	in := fullClosureInput()
	in.Date = time.Time{} // zero

	path, err := g.GenerateClosureLog(context.Background(), in)
	if err != nil {
		t.Fatalf("GenerateClosureLog error: %v", err)
	}

	today := time.Now().UTC().Format("2006-01-02")
	base := filepath.Base(path)
	if !strings.HasPrefix(base, today+"-") {
		t.Errorf("filename %q does not start with today's UTC date %q", base, today)
	}
}

// TestGenerateClosureLog_OptionalFieldsOmitted confirms optional sections
// (Challenge Test, FixCommitSHA, Subtitle, Stack, Device) are absent
// from the rendered output when empty — not merely empty headings.
func TestGenerateClosureLog_OptionalFieldsOmitted(t *testing.T) {
	dir := t.TempDir()
	g := NewGenerator(dir)

	in := ClosureLogInput{
		CrashlyticsID:   "b00b00b00b00b00b00b00b00b00b00b0",
		Slug:            "minimal-closure",
		Date:            time.Date(2026, 5, 16, 0, 0, 0, 0, time.UTC),
		Title:           "Minimal closure log",
		Type:            "NON_FATAL",
		Version:         "1.2.20 (1040) debug",
		StateAtClosure:  "OPEN (auto-closed by adapter)",
		RootCause:       "Root cause text.",
		Fix:             "Fix text.",
		ValidationTest:  "internal/foo/foo_test.go",
		ClosureProtocol: "Closure protocol text.",
		// ChallengeTest, FixCommitSHA, Subtitle, Stack, Device left empty
	}

	path, err := g.GenerateClosureLog(context.Background(), in)
	if err != nil {
		t.Fatalf("GenerateClosureLog error: %v", err)
	}
	content, _ := os.ReadFile(path)
	s := string(content)

	// Absent sections MUST NOT appear.
	absent := []string{
		"**Subtitle:**",
		"**Stack:**",
		"**Device:**",
		"**Fix commit:**",
		"## Challenge Test",
	}
	for _, fragment := range absent {
		if strings.Contains(s, fragment) {
			t.Errorf("rendered markdown contains %q which should have been omitted (empty input)\n%s", fragment, s)
		}
	}
}

// TestGenerateClosureLog_SchemaMatchesExistingLogs is the §6.J.3
// indistinguishable-from-manual assertion. The rendered output's headings
// MUST match the canonical §6.O schema headings that every existing log
// uses. Mutating the renderer (e.g., "## Root cause" → "## Cause") makes
// this test fail.
func TestGenerateClosureLog_SchemaMatchesExistingLogs(t *testing.T) {
	dir := t.TempDir()
	g := NewGenerator(dir)

	path, err := g.GenerateClosureLog(context.Background(), fullClosureInput())
	if err != nil {
		t.Fatalf("GenerateClosureLog error: %v", err)
	}
	content, _ := os.ReadFile(path)
	s := string(content)

	// Schema constants — these MUST be byte-identical to the headings
	// across every file in .lava-ci-evidence/crashlytics-resolved/.
	schemaHeadings := []string{
		"# Crashlytics issue ",
		"**Issue ID:**",
		"**Title:**",
		"**Type:**",
		"**Version:**",
		"**State at closure:**",
		"## Root cause",
		"## Fix",
		"## Validation test (per §6.O + §6.AB)",
		"## Closure protocol",
	}
	for _, h := range schemaHeadings {
		if !strings.Contains(s, h) {
			t.Errorf("§6.O schema heading %q missing — rendered output:\n%s", h, s)
		}
	}
}

// TestGenerateClosureLog_SlugSanitization confirms the slug normalizer
// strips unsafe filename characters consistently across uppercase + spaces
// + special chars.
func TestGenerateClosureLog_SlugSanitization(t *testing.T) {
	tests := []struct {
		name     string
		inSlug   string
		wantName string
	}{
		{"lowercase passthrough", "abc-def", "2026-05-16-abc-def.md"},
		{"uppercase folded", "ABC-DEF", "2026-05-16-abc-def.md"},
		{"spaces to hyphens", "abc def ghi", "2026-05-16-abc-def-ghi.md"},
		{"special chars stripped", "abc!@#$%^&def", "2026-05-16-abc-def.md"},
		{"collapsed multi-hyphens", "abc---def", "2026-05-16-abc-def.md"},
		{"trimmed edge hyphens", "---abc---", "2026-05-16-abc.md"},
		{"underscore to hyphen", "abc_def_ghi", "2026-05-16-abc-def-ghi.md"},
		{"digits preserved", "abc123def", "2026-05-16-abc123def.md"},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			g := NewGenerator(dir)
			in := fullClosureInput()
			in.Slug = tc.inSlug
			in.Date = time.Date(2026, 5, 16, 0, 0, 0, 0, time.UTC)
			path, err := g.GenerateClosureLog(context.Background(), in)
			if err != nil {
				t.Fatalf("err: %v", err)
			}
			if got := filepath.Base(path); got != tc.wantName {
				t.Errorf("filename = %q; want %q", got, tc.wantName)
			}
		})
	}
}

// TestGenerateClosureLog_CreatesOutputDirOnDemand confirms first-write
// MkdirAll happens (constructor does not create dir, GenerateClosureLog
// does).
func TestGenerateClosureLog_CreatesOutputDirOnDemand(t *testing.T) {
	parent := t.TempDir()
	dir := filepath.Join(parent, "nested", "closure-logs")
	g := NewGenerator(dir)

	if _, err := os.Stat(dir); !os.IsNotExist(err) {
		t.Fatalf("dir already exists before write: %v", err)
	}

	_, err := g.GenerateClosureLog(context.Background(), fullClosureInput())
	if err != nil {
		t.Fatalf("GenerateClosureLog error: %v", err)
	}

	if _, err := os.Stat(dir); err != nil {
		t.Errorf("output dir not created on demand: %v", err)
	}
}

// TestGenerateClosureLog_ConcurrentSafe stress-tests the mutex around the
// wrapped HelixQA Generator. The HelixQA Generator's counter is not
// goroutine-safe; the adapter wraps the call with a mutex. Without the
// mutex this test surfaces a data race under `-race`.
func TestGenerateClosureLog_ConcurrentSafe(t *testing.T) {
	dir := t.TempDir()
	g := NewGenerator(dir)

	const n = 20
	var wg sync.WaitGroup
	for i := 0; i < n; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			in := fullClosureInput()
			in.Slug = "concurrent-" + string(rune('a'+(i%26)))
			in.Date = time.Date(2026, 5, 16, 0, 0, 0, 0, time.UTC)
			in.CrashlyticsID = "id-" + in.Slug
			if _, err := g.GenerateClosureLog(context.Background(), in); err != nil {
				t.Errorf("concurrent #%d error: %v", i, err)
			}
		}(i)
	}
	wg.Wait()

	// At least 26 distinct files (n>26 collides on slug after mod, but
	// the file write is overwrite-safe — what we're checking is "no
	// panic, no race, all goroutines completed").
	entries, _ := os.ReadDir(dir)
	if len(entries) < 1 {
		t.Errorf("expected at least one file written; got %d", len(entries))
	}
}

// TestSanitizeSlug_EmptyInput exercises the helper's empty-input branch
// directly. The slug-validation in GenerateClosureLog rejects empty
// before this helper is called, but the helper's behavior on empty
// input is documented as "" and we lock it down.
func TestSanitizeSlug_EmptyInput(t *testing.T) {
	if got := sanitizeSlug(""); got != "" {
		t.Errorf("sanitizeSlug(\"\") = %q; want \"\"", got)
	}
}

// TestRenderClosureLog_NormalizesWhitespace verifies that TrimSpace on
// the body sections strips leading/trailing whitespace consistently.
func TestRenderClosureLog_NormalizesWhitespace(t *testing.T) {
	in := ClosureLogInput{
		CrashlyticsID:   "abc",
		Slug:            "x",
		Date:            time.Date(2026, 5, 16, 0, 0, 0, 0, time.UTC),
		Title:           "T",
		Type:            "F",
		Version:         "V",
		StateAtClosure:  "S",
		RootCause:       "\n\n  root cause text  \n\n",
		Fix:             "\n  fix text  \n",
		ValidationTest:  "  validation  ",
		ClosureProtocol: "  closure  ",
	}
	content := renderClosureLog(in, in.Date)
	s := string(content)

	// Each body section's text should appear without the leading/
	// trailing whitespace.
	for _, frag := range []string{"root cause text", "fix text", "validation", "closure"} {
		if !strings.Contains(s, frag) {
			t.Errorf("expected trimmed fragment %q in output:\n%s", frag, s)
		}
	}
}
