// Phase 4-C-3 — REAL-STACK integration test for internal/qa/ticket.
//
// Per docs/plans/2026-05-16-helixqa-go-package-linking-design.md §D.3:
// gated by the `helixqa_realstack` build tag. Default `go test ./...`
// runs skip this file (transitive HelixQA deps may not be present in
// every CI environment; running this test requires the sibling
// submodules/helixqa/ present + module-graph resolved).
//
// Per §6.J / §6.AE.4: exercises the REAL HelixQA Generator against
// the REAL filesystem. The adapter is the SUT; nothing in this test
// mocks HelixQA. Falsifiability rehearsal recorded in the Phase 4-C-3
// commit body.
//
// Run with:
//   go test -tags=helixqa_realstack ./tests/qa/...

//go:build helixqa_realstack

package qa_test

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	qaticket "digital.vasic.lava.apigo/internal/qa/ticket"
)

// TestTicketAdapter_RealStack_ProducesClosureLogMatchingSchema exercises
// the full happy path end-to-end: adapter → real HelixQA Generator →
// real filesystem → on-disk markdown that schema-matches every existing
// file under .lava-ci-evidence/crashlytics-resolved/.
//
// This is the §6.AE.4 acceptance-gate test that proves a real consumer
// can write a §6.O-compliant closure log programmatically.
func TestTicketAdapter_RealStack_ProducesClosureLogMatchingSchema(t *testing.T) {
	dir := t.TempDir()
	g := qaticket.NewGenerator(dir)

	in := qaticket.ClosureLogInput{
		CrashlyticsID:   "realstack-issue-id-12345",
		Slug:            "realstack-smoke-test",
		Date:            time.Date(2026, 5, 16, 12, 0, 0, 0, time.UTC),
		Title:           "Real-stack smoke test closure",
		Subtitle:        "smoke test",
		Stack:           "frame 1 → frame 2 → frame 3",
		Type:            "FATAL",
		Device:          "Test device (real-stack)",
		Version:         "1.2.20 (1040) real-stack",
		StateAtClosure:  "OPEN (auto-closed by real-stack test)",
		RootCause:       "Root cause analysis — real-stack test placeholder.",
		Fix:             "Fix description — real-stack test placeholder.",
		ValidationTest:  "lava-api-go/internal/qa/ticket/generator_test.go",
		ChallengeTest:   "lava-api-go/tests/qa/ticket_test.go (this file)",
		ClosureProtocol: "Real-stack closure protocol.",
		FixCommitSHA:    "deadbeefcafebabe",
		Labels:          []string{"realstack", "phase-4-c-3"},
	}

	path, err := g.GenerateClosureLog(context.Background(), in)
	if err != nil {
		t.Fatalf("GenerateClosureLog: %v", err)
	}

	// 1. Filename matches §6.O convention.
	if want := "2026-05-16-realstack-smoke-test.md"; filepath.Base(path) != want {
		t.Errorf("filename = %q; want %q", filepath.Base(path), want)
	}

	// 2. File is real, non-empty, readable.
	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat written file: %v", err)
	}
	if info.Size() == 0 {
		t.Fatalf("written file is empty")
	}

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read file: %v", err)
	}
	s := string(content)

	// 3. Every required §6.O section heading present (canonical
	// shape — matches every existing file under
	// .lava-ci-evidence/crashlytics-resolved/).
	requiredHeadings := []string{
		"# Crashlytics issue realstack-issue-id-12345 — closure log",
		"**Issue ID:** `realstack-issue-id-12345`",
		"**Title:** `Real-stack smoke test closure`",
		"**Type:** FATAL",
		"**Device:** Test device (real-stack)",
		"**Version:** 1.2.20 (1040) real-stack",
		"**State at closure:** OPEN (auto-closed by real-stack test)",
		"**Closure date:** 2026-05-16",
		"**Fix commit:** `deadbeefcafebabe`",
		"## Root cause",
		"## Fix",
		"## Validation test (per §6.O + §6.AB)",
		"## Challenge Test (per §6.O + §6.AE)",
		"## Closure protocol",
	}
	for _, h := range requiredHeadings {
		if !strings.Contains(s, h) {
			t.Errorf("required heading %q missing — generated output:\n%s", h, s)
		}
	}

	// 4. Trailer identifies origin (per §6.J: adapter is honest about
	// its provenance — operators reading the file can see it was
	// generated, not hand-authored).
	if !strings.Contains(s, "Generated by lava-api-go/internal/qa/ticket") {
		t.Errorf("trailer missing — operators can't distinguish adapter-generated from hand-authored\n%s", s)
	}
}

// TestTicketAdapter_RealStack_MultipleLogsSameDay verifies a single
// Generator instance can write multiple closure logs without state
// corruption (different slugs → different filenames; same day, no
// collision).
func TestTicketAdapter_RealStack_MultipleLogsSameDay(t *testing.T) {
	dir := t.TempDir()
	g := qaticket.NewGenerator(dir)

	base := qaticket.ClosureLogInput{
		Date:            time.Date(2026, 5, 16, 12, 0, 0, 0, time.UTC),
		Title:           "Title",
		Type:            "FATAL",
		Version:         "v1",
		StateAtClosure:  "OPEN",
		RootCause:       "rc",
		Fix:             "fix",
		ValidationTest:  "vt",
		ClosureProtocol: "cp",
	}

	slugs := []string{"alpha", "beta", "gamma"}
	for _, slug := range slugs {
		in := base
		in.CrashlyticsID = "id-" + slug
		in.Slug = slug
		if _, err := g.GenerateClosureLog(context.Background(), in); err != nil {
			t.Fatalf("GenerateClosureLog(%s): %v", slug, err)
		}
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read dir: %v", err)
	}
	if len(entries) != len(slugs) {
		t.Errorf("entries = %d; want %d", len(entries), len(slugs))
	}

	// Each slug has its own file.
	for _, slug := range slugs {
		want := "2026-05-16-" + slug + ".md"
		_, err := os.Stat(filepath.Join(dir, want))
		if err != nil {
			t.Errorf("expected file %q not found: %v", want, err)
		}
	}
}
