#!/usr/bin/env bash
# Hermetic test suite for scripts/pipeline/phase-04-live-verify-api.sh's
# per-request PASS/FAIL policy.
#
# The fixture is a REAL TLS HTTP server (python3 http.server + ssl, a
# self-signed cert generated by openssl into mktemp -d, bound to an
# ephemeral port chosen by the kernel — no port literal anywhere, per §6.R)
# together with a disposable repo whose .env declares that port as
# LAVA_API_LISTEN. The script under test is therefore the REAL phase-04
# script making REAL curl requests over REAL TLS; only the service on the
# other end is a stub. Nothing here touches Gradle, ADB, an emulator, or the
# operator's actual lava-api.service.
#
# WHY CASE 1 EXISTS (forensic anchor, 2026-08-21, vacuous-pass hunt):
# this script's own header states its reason for existing — phase-03 already
# proves the container is "Up", and what THIS phase adds is proof that the
# running service "genuinely answers REAL application-level HTTP requests
# with REAL, meaningful response bodies — not merely that its
# process/container lifecycle is 'Up' (§6.B)". But its per-request verdict
# was computed from two things only: curl's exit code, and a 2xx status
# match. The response body was read, truncated to 300 chars, interpolated
# into the assertion_summary — and never asserted on.
#
# So a server that answers every request with HTTP 200 and a ZERO-BYTE body
# passed the whole phase. Verbatim output from a real run of the unfixed
# script against exactly this fixture:
#
#   phase-04-live-verify-api: SUMMARY
#     base URL:            https://127.0.0.1:44373
#     requests attempted:  3
#       .../lava-api-go-live-verify-health.json (anti_bluff_status=validated)
#       .../lava-api-go-live-verify-ready.json (anti_bluff_status=validated)
#       .../lava-api-go-live-verify-providers.json (anti_bluff_status=validated)
#     phase result:        PASS
#   PHASE EXIT=0
#
#   {"test_id":"lava-api-go-live-verify-providers","result":"PASS",
#    "anti_bluff_status":"validated",
#    "assertion_summary":"GET /providers against the real running lava-api-go
#     service at https://.../providers returned HTTP 200 with response body: "}
#
# Note where that assertion_summary ends: "...response body: " — nothing
# after the colon. Three Evidence Records claiming the provider catalogue was
# served, all anti-bluff-validated, none containing a single byte the server
# actually sent. The anti-bluff validator could not catch it either: its
# rule 3 (raw_output_ref must be non-empty) was satisfied by the scaffolding
# lines THIS script writes into the raw file itself ("command:",
# "curl_exit_code:", "http_status:", "response_body:"), which are present
# whether or not the server said anything.
#
# The real service does not behave this way — /health returns
# {"status":"alive"}, /ready returns {"status":"ready"}, /providers returns
# the provider catalogue (lava-api-go/internal/observability/health.go and
# internal/router/router.go, read directly) — so requiring a non-empty body
# rejects nothing the real service legitimately does. CASE 2 pins that down.
#
# Exit 0 if every case passes; non-zero otherwise.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PHASE04="${REPO_ROOT}/scripts/pipeline/phase-04-live-verify-api.sh"

if [[ ! -f "$PHASE04" ]]; then
  echo "FAIL: script under test not found: $PHASE04"
  exit 1
fi
for tool in jq git python3 curl openssl; do
  command -v "$tool" >/dev/null 2>&1 || { echo "FAIL: '$tool' required"; exit 1; }
done

FAILURES=0
pass() { echo "PASS: $1"; }
fail() { echo "FAIL: $1"; FAILURES=$((FAILURES + 1)); }

WORKDIR="$(mktemp -d)"
SERVER_PID=""
cleanup() {
  [[ -n "$SERVER_PID" ]] && kill "$SERVER_PID" 2>/dev/null
  rm -rf -- "$WORKDIR"
}
trap cleanup EXIT

# One self-signed cert for every fixture server in this suite.
openssl req -x509 -newkey rsa:2048 -nodes \
  -keyout "${WORKDIR}/key.pem" -out "${WORKDIR}/cert.pem" \
  -days 1 -subj "/CN=localhost" >/dev/null 2>&1

# A real TLS server whose reply shape is chosen by argv[4]:
#   empty-200 -> 200 with a zero-byte body
#   real-json -> 200 with a real JSON body per endpoint
#   error-500 -> 500 with a real error body
cat > "${WORKDIR}/fixture_server.py" <<'PY'
import http.server, ssl, socket, sys

MODE = sys.argv[4]

BODIES = {
    "/health": b'{"status":"alive"}',
    "/ready": b'{"status":"ready"}',
    "/providers": b'{"providers":[{"id":"rutracker","authType":"FORM_LOGIN"}]}',
}


class Handler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        if MODE == "empty-200":
            self.send_response(200)
            self.send_header("Content-Length", "0")
            self.end_headers()
            return
        if MODE == "error-500":
            body = b'{"error":"internal"}'
            self.send_response(500)
        else:
            body = BODIES.get(self.path, b'{"ok":true}')
            self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, *args):
        pass


probe = socket.socket()
probe.bind(("", 0))
port = probe.getsockname()[1]
probe.close()

httpd = http.server.HTTPServer(("", port), Handler)
ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
ctx.load_cert_chain(sys.argv[1], sys.argv[2])
httpd.socket = ctx.wrap_socket(httpd.socket, server_side=True)
with open(sys.argv[3], "w") as f:
    f.write(str(port))
httpd.serve_forever()
PY

# _start_server <mode> — starts the fixture server, sets SERVER_PID and PORT.
_start_server() {
  local mode="$1"
  local port_file="${WORKDIR}/port.${mode}"
  rm -f "$port_file"
  python3 "${WORKDIR}/fixture_server.py" \
    "${WORKDIR}/cert.pem" "${WORKDIR}/key.pem" "$port_file" "$mode" &
  SERVER_PID=$!
  local i
  for i in $(seq 1 100); do
    [[ -s "$port_file" ]] && break
    sleep 0.1
  done
  if [[ ! -s "$port_file" ]]; then
    echo "FAIL: fixture TLS server did not come up"
    exit 1
  fi
  PORT="$(cat "$port_file")"
}

_stop_server() {
  [[ -n "$SERVER_PID" ]] && kill "$SERVER_PID" 2>/dev/null
  wait "$SERVER_PID" 2>/dev/null || true
  SERVER_PID=""
}

# _new_repo <name> <port> — disposable repo whose .env points phase-04 at
# the fixture server's ephemeral port. Prints the repo path.
_new_repo() {
  local name="$1" port="$2"
  local dir="${WORKDIR}/${name}"
  git init -q -b master "$dir"
  git -C "$dir" config user.email "fixture@example.invalid"
  git -C "$dir" config user.name "Fixture"
  printf 'x\n' > "${dir}/f"
  printf '.env\n.lava-ci-evidence/\n' > "${dir}/.gitignore"
  git -C "$dir" add -A >/dev/null 2>&1
  git -C "$dir" commit -qm "fixture" >/dev/null 2>&1
  printf 'LAVA_API_LISTEN=:%s\n' "$port" > "${dir}/.env"
  printf '%s' "$dir"
}

# _run_phase04 <repo-dir> <run_id> — sets P4_RC and P4_OUT.
_run_phase04() {
  local dir="$1" run_id="$2"
  ( cd "$dir" && source "${REPO_ROOT}/scripts/pipeline/lib/run-report.sh" && \
    init_run_report "$run_id" "$(git -C "$dir" rev-parse HEAD)" >/dev/null )
  local out_file="${WORKDIR}/phase04-${run_id}.log"
  set +e
  ( cd "$dir" && bash "$PHASE04" "$run_id" "$dir" ) >"$out_file" 2>&1
  P4_RC=$?
  set -e
  P4_OUT="$(cat "$out_file")"
}

_report() { printf '%s/.lava-ci-evidence/pipeline-runs/%s/report.json' "$1" "$2"; }
_records() { find "$1/.lava-ci-evidence/pipeline-runs/$2/phase-04" -name '*.json' -type f 2>/dev/null; }

echo "==============================================================="
echo "CASE 1 (LOAD-BEARING): every endpoint answers 200 with a"
echo "ZERO-BYTE body — the phase must not report success"
echo "==============================================================="
echo "This phase exists to prove the service answers with real,"
echo "meaningful response bodies. A 200 with no body proves only that"
echo "a socket answered — exactly the §6.B 'Up is not healthy' bluff"
echo "one layer up, which is what this phase is for."
echo ""

_start_server empty-200
RUN_A="2026-08-21T04-00-00Z"
DIR_A="$(_new_repo emptybody "$PORT")"
_run_phase04 "$DIR_A" "$RUN_A"
_stop_server

if grep -q "http_status: 200" <<< "$P4_OUT"; then
  pass "fixture sanity: the server really did answer HTTP 200"
else
  fail "fixture sanity: no HTTP 200 seen, so this case proves nothing; output: ${P4_OUT}"
fi

if [[ "$P4_RC" -ne 0 ]]; then
  pass "200 with an empty body -> non-zero exit (${P4_RC})"
else
  fail "200 with an empty body -> exit 0. Three Evidence Records claimed the real service answered, each ending 'with response body: ' and nothing after it."
fi

res_a="$(jq -r '.phases[] | select(.name=="live_verify") | .result' "$(_report "$DIR_A" "$RUN_A")" 2>/dev/null)"
if [[ "$res_a" == "FAIL" ]]; then
  pass "200 with an empty body: report.json records live_verify phase FAIL"
else
  fail "200 with an empty body: live_verify phase result is '${res_a}', expected FAIL"
fi

empty_pass=0
while IFS= read -r rec; do
  [[ -z "$rec" ]] && continue
  if [[ "$(jq -r '.result' "$rec")" == "PASS" ]]; then
    empty_pass=$((empty_pass + 1))
    echo "    still PASS: $(jq -r '.test_id' "$rec") :: $(jq -r '.assertion_summary' "$rec")"
  fi
done < <(_records "$DIR_A" "$RUN_A")
if [[ "$empty_pass" -eq 0 ]]; then
  pass "200 with an empty body: no Evidence Record claims PASS"
else
  fail "${empty_pass} Evidence Record(s) claim PASS on a response that carried no bytes"
fi

echo ""
echo "==============================================================="
echo "CASE 2: real JSON bodies -> PASS"
echo "(guards against a 'fix' that just fails every live check; these"
echo "are the exact bodies the real lava-api-go handlers return)"
echo "==============================================================="

_start_server real-json
RUN_B="2026-08-21T05-00-00Z"
DIR_B="$(_new_repo realbody "$PORT")"
_run_phase04 "$DIR_B" "$RUN_B"
_stop_server

if [[ "$P4_RC" -eq 0 ]]; then
  pass "real JSON bodies -> exit 0"
else
  fail "real JSON bodies -> exit ${P4_RC}, expected 0; output: ${P4_OUT}"
fi
res_b="$(jq -r '.phases[] | select(.name=="live_verify") | .result' "$(_report "$DIR_B" "$RUN_B")" 2>/dev/null)"
if [[ "$res_b" == "PASS" ]]; then
  pass "real JSON bodies: report.json records live_verify phase PASS"
else
  fail "real JSON bodies: live_verify phase result is '${res_b}', expected PASS"
fi

rec_count=0
bad=0
while IFS= read -r rec; do
  [[ -z "$rec" ]] && continue
  rec_count=$((rec_count + 1))
  [[ "$(jq -r '.result' "$rec")" == "PASS" ]] || bad=$((bad + 1))
  [[ "$(jq -r '.anti_bluff_status' "$rec")" == "validated" ]] || bad=$((bad + 1))
done < <(_records "$DIR_B" "$RUN_B")
if [[ "$rec_count" -eq 3 && "$bad" -eq 0 ]]; then
  pass "real JSON bodies: all 3 Evidence Records are PASS and validated"
else
  fail "real JSON bodies: ${rec_count} record(s) found, ${bad} not PASS/validated"
fi

body_seen="$(jq -r '.assertion_summary' "$(_records "$DIR_B" "$RUN_B" | head -1)")"
if grep -q '{' <<< "$body_seen"; then
  pass "real JSON bodies: the assertion_summary quotes real bytes from the server"
else
  fail "real JSON bodies: assertion_summary carries no response content: ${body_seen}"
fi

echo ""
echo "==============================================================="
echo "CASE 3: non-2xx still fails (pre-existing guard, must not regress)"
echo "==============================================================="

_start_server error-500
RUN_C="2026-08-21T05-30-00Z"
DIR_C="$(_new_repo errorbody "$PORT")"
_run_phase04 "$DIR_C" "$RUN_C"
_stop_server

if [[ "$P4_RC" -ne 0 ]] && grep -q "non-2xx HTTP status 500" <<< "$P4_OUT"; then
  pass "HTTP 500 with a real body -> non-zero exit, reported as non-2xx"
else
  fail "HTTP 500 -> exit ${P4_RC} without the expected non-2xx refusal; output: ${P4_OUT}"
fi

echo ""
echo "==============================================================="
if [[ "$FAILURES" -eq 0 ]]; then
  echo "ALL CHECKS PASSED"
  exit 0
else
  echo "$FAILURES CHECK(S) FAILED"
  exit 1
fi
